version: "3.7"

services:
  app:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - api

  nginx:
    image: nginx:1.17-alpine
    container_name: api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - api

networks:
  api:
    driver: bridge
